//
// FILE            ldCoreTermIds.c
//
// AUTHOR          Ken Zangelin
//
// Copyright 2026 Seamware
// SPDX-License-Identifier: Apache-2.0
//
#include "corLog/corLog.h"                           // COR_E
#include "corJsonld/corLdInit.h"                     // corLdCoreTermIdsSet

#include "corNgsild/CorTerm.h"                       // CorTerm
#include "corNgsild/ldCoreTermIds.h"                 // Own interface



// -----------------------------------------------------------------------------
//
// ldCoreTermNameV - the name of each CorTerm, indexed by it
//
// Designated initializers: an entry cannot drift to another index when the enum grows,
// and a missing one is NULL, which ldCoreTermIdsInit reports.
//
const char* ldCoreTermNameV[CorTermLast] =
{
  [CorTermNgsiLd]                         = "ngsi-ld",
  [CorTermGeojson]                        = "geojson",
  [CorTermId]                             = "id",
  [CorTermType]                           = "type",
  [CorTermAttribute]                      = "Attribute",
  [CorTermAttributeListType]              = "AttributeList",
  [CorTermContextSourceIdentity]          = "ContextSourceIdentity",
  [CorTermContextSourceNotification]      = "ContextSourceNotification",
  [CorTermContextSourceRegistration]      = "ContextSourceRegistration",
  [CorTermDate]                           = "Date",
  [CorTermDateTime]                       = "DateTime",
  [CorTermEntityMapType]                  = "EntityMap",
  [CorTermEntityType]                     = "EntityType",
  [CorTermEntityTypeInfo]                 = "EntityTypeInfo",
  [CorTermEntityTypeList]                 = "EntityTypeList",
  [CorTermExecutionResultDetails]         = "ExecutionResultDetails",
  [CorTermFeature]                        = "Feature",
  [CorTermFeatureCollection]              = "FeatureCollection",
  [CorTermGeoProperty]                = "GeoProperty",
  [CorTermGeometryCollection]             = "GeometryCollection",
  [CorTermJsonProperty]                   = "JsonProperty",
  [CorTermLanguageProperty]               = "LanguageProperty",
  [CorTermLineString]                     = "LineString",
  [CorTermListProperty]                   = "ListProperty",
  [CorTermListRelationship]               = "ListRelationship",
  [CorTermMultiLineString]                = "MultiLineString",
  [CorTermMultiPoint]                     = "MultiPoint",
  [CorTermMultiPolygon]                   = "MultiPolygon",
  [CorTermNotificationType]               = "Notification",
  [CorTermPoint]                          = "Point",
  [CorTermPolygon]                        = "Polygon",
  [CorTermProperty]                       = "Property",
  [CorTermRelationship]                   = "Relationship",
  [CorTermSnapshot]                       = "Snapshot",
  [CorTermSnapshotNotification]           = "SnapshotNotification",
  [CorTermSubscription]                   = "Subscription",
  [CorTermTemporalProperty]               = "TemporalProperty",
  [CorTermTime]                           = "Time",
  [CorTermVocabProperty]                  = "VocabProperty",
  [CorTermAccept]                         = "accept",
  [CorTermAggrParams]                     = "aggrParams",
  [CorTermAggrMethods]                    = "aggrMethods",
  [CorTermAggrPeriodDuration]             = "aggrPeriodDuration",
  [CorTermAttributeCount]                 = "attributeCount",
  [CorTermAttributeDetails]               = "attributeDetails",
  [CorTermAttributeList]                  = "attributeList",
  [CorTermAttributeName]                  = "attributeName",
  [CorTermAttributeNames]                 = "attributeNames",
  [CorTermAttributeTypes]                 = "attributeTypes",
  [CorTermAttributes]                     = "attributes",
  [CorTermAttrs]                          = "attrs",
  [CorTermAvg]                            = "avg",
  [CorTermBbox]                           = "bbox",
  [CorTermCacheDuration]                  = "cacheDuration",
  [CorTermCollation]                      = "collation",
  [CorTermContainedBy]                    = "containedBy",
  [CorTermContextSourceAlias]             = "contextSourceAlias",
  [CorTermContextSourceExtras]            = "contextSourceExtras",
  [CorTermContextSourceInfo]              = "contextSourceInfo",
  [CorTermContextSourceTimeAt]            = "contextSourceTimeAt",
  [CorTermContextSourceUptime]            = "contextSourceUptime",
  [CorTermCooldown]                       = "cooldown",
  [CorTermCoordinates]                    = "coordinates",
  [CorTermCreatedAt]                      = "createdAt",
  [CorTermCsf]                            = "csf",
  [CorTermData]                           = "data",
  [CorTermDataset]                        = "dataset",
  [CorTermDatasetId]                      = "datasetId",
  [CorTermDeletedAt]                      = "deletedAt",
  [CorTermDescription]                    = "description",
  [CorTermDetail]                         = "detail",
  [CorTermDistinctCount]                  = "distinctCount",
  [CorTermEndAt]                          = "endAt",
  [CorTermEndTimeAt]                      = "endTimeAt",
  [CorTermEndpoint]                       = "endpoint",
  [CorTermEntities]                       = "entities",
  [CorTermEntity]                         = "entity",
  [CorTermEntityCount]                    = "entityCount",
  [CorTermEntityId]                       = "entityId",
  [CorTermEntityList]                     = "entityList",
  [CorTermEntityMap]                      = "entityMap",
  [CorTermEntityMapLifetime]              = "entityMapLifetime",
  [CorTermError]                          = "error",
  [CorTermErrors]                         = "errors",
  [CorTermExpandValues]                   = "expandValues",
  [CorTermExpiresAt]                      = "expiresAt",
  [CorTermFeatures]                       = "features",
  [CorTermFormat]                         = "format",
  [CorTermGeoQ]                           = "geoQ",
  [CorTermGeometry]                       = "geometry",
  [CorTermGeoproperty]                    = "geoproperty",
  [CorTermGeorel]                         = "georel",
  [CorTermIdPattern]                      = "idPattern",
  [CorTermInformation]                    = "information",
  [CorTermInstanceId]                     = "instanceId",
  [CorTermIsActive]                       = "isActive",
  [CorTermJoin]                           = "join",
  [CorTermJoinLevel]                      = "joinLevel",
  [CorTermJson]                           = "json",
  [CorTermJsonKeys]                       = "jsonKeys",
  [CorTermJsonldContext]                  = "jsonldContext",
  [CorTermJsons]                          = "jsons",
  [CorTermKey]                            = "key",
  [CorTermLang]                           = "lang",
  [CorTermLanguageMap]                    = "languageMap",
  [CorTermLanguageMaps]                   = "languageMaps",
  [CorTermLangString]                     = "langString",
  [CorTermLastFailure]                    = "lastFailure",
  [CorTermLastN]                          = "lastN",
  [CorTermLastNotification]               = "lastNotification",
  [CorTermLastSuccess]                    = "lastSuccess",
  [CorTermLastUsedAt]                     = "lastUsedAt",
  [CorTermLinkedMaps]                     = "linkedMaps",
  [CorTermLocalOnly]                      = "localOnly",
  [CorTermLocation]                       = "location",
  [CorTermManagement]                     = "management",
  [CorTermManagementInterval]             = "managementInterval",
  [CorTermMax]                            = "max",
  [CorTermMin]                            = "min",
  [CorTermMode]                           = "mode",
  [CorTermModifiedAt]                     = "modifiedAt",
  [CorTermNgsildproof]                    = "ngsildproof",
  [CorTermNgsildConformance]              = "ngsildConformance",
  [CorTermNotification]                   = "notification",
  [CorTermNotificationTrigger]            = "notificationTrigger",
  [CorTermNotifiedAt]                     = "notifiedAt",
  [CorTermNotifierInfo]                   = "notifierInfo",
  [CorTermNotUpdated]                     = "notUpdated",
  [CorTermObject]                         = "object",
  [CorTermObjectList]                     = "objectList",
  [CorTermObjectLists]                    = "objectLists",
  [CorTermObjects]                        = "objects",
  [CorTermObjectType]                     = "objectType",
  [CorTermObservationInterval]            = "observationInterval",
  [CorTermObservationSpace]               = "observationSpace",
  [CorTermObservedAt]                     = "observedAt",
  [CorTermOmit]                           = "omit",
  [CorTermOperations]                     = "operations",
  [CorTermOperationSpace]                 = "operationSpace",
  [CorTermOrderBy]                        = "orderBy",
  [CorTermOrdering]                       = "ordering",
  [CorTermPick]                           = "pick",
  [CorTermPreviousJson]                   = "previousJson",
  [CorTermPreviousLanguageMap]            = "previousLanguageMap",
  [CorTermPreviousObject]                 = "previousObject",
  [CorTermPreviousObjectList]             = "previousObjectList",
  [CorTermPreviousValue]                  = "previousValue",
  [CorTermPreviousValueList]              = "previousValueList",
  [CorTermPreviousVocab]                  = "previousVocab",
  [CorTermProblemDetails]                 = "problemDetails",
  [CorTermProperties]                     = "properties",
  [CorTermPropertyNames]                  = "propertyNames",
  [CorTermQ]                              = "q",
  [CorTermReason]                         = "reason",
  [CorTermReceiverInfo]                   = "receiverInfo",
  [CorTermRefreshRate]                    = "refreshRate",
  [CorTermRegistrationId]                 = "registrationId",
  [CorTermRegistrationName]               = "registrationName",
  [CorTermRelationshipNames]              = "relationshipNames",
  [CorTermResultStatus]                   = "resultStatus",
  [CorTermScope]                          = "scope",
  [CorTermScopeQ]                         = "scopeQ",
  [CorTermShowChanges]                    = "showChanges",
  [CorTermSnapshotId]                     = "snapshotId",
  [CorTermSnapshotLifetime]               = "snapshotLifetime",
  [CorTermSnapshotPriority]               = "snapshotPriority",
  [CorTermSnapshotQueries]                = "snapshotQueries",
  [CorTermSnapshotQueriesDetails]         = "snapshotQueriesDetails",
  [CorTermSnapshotStatus]                 = "snapshotStatus",
  [CorTermSnapshotTemporalQueries]        = "snapshotTemporalQueries",
  [CorTermSnapshotTemporalQueriesDetails] = "snapshotTemporalQueriesDetails",
  [CorTermSplitEntities]                  = "splitEntities",
  [CorTermStartAt]                        = "startAt",
  [CorTermStatus]                         = "status",
  [CorTermStddev]                         = "stddev",
  [CorTermSubscriptionId]                 = "subscriptionId",
  [CorTermSubscriptionName]               = "subscriptionName",
  [CorTermSuccess]                        = "success",
  [CorTermSum]                            = "sum",
  [CorTermSumsq]                          = "sumsq",
  [CorTermSysAttrs]                       = "sysAttrs",
  [CorTermTemporalQ]                      = "temporalQ",
  [CorTermTenant]                         = "tenant",
  [CorTermThrottling]                     = "throttling",
  [CorTermTimeAt]                         = "timeAt",
  [CorTermTimeInterval]                   = "timeInterval",
  [CorTermTimeout]                        = "timeout",
  [CorTermTimeproperty]                   = "timeproperty",
  [CorTermTimerel]                        = "timerel",
  [CorTermTimesFailed]                    = "timesFailed",
  [CorTermTimesSent]                      = "timesSent",
  [CorTermTitle]                          = "title",
  [CorTermTotalCount]                     = "totalCount",
  [CorTermTriggerReason]                  = "triggerReason",
  [CorTermTypeList]                       = "typeList",
  [CorTermTypeName]                       = "typeName",
  [CorTermTypeNames]                      = "typeNames",
  [CorTermUnchanged]                      = "unchanged",
  [CorTermUnitCode]                       = "unitCode",
  [CorTermUpdated]                        = "updated",
  [CorTermUri]                            = "uri",
  [CorTermValue]                          = "value",
  [CorTermValueList]                      = "valueList",
  [CorTermValueLists]                     = "valueLists",
  [CorTermValues]                         = "values",
  [CorTermValueType]                      = "valueType",
  [CorTermVocab]                          = "vocab",
  [CorTermVocabs]                         = "vocabs",
  [CorTermWatchedAttributes]              = "watchedAttributes",
  [CorTermContextBridge]                  = "ContextBridge",
  [CorTermChannel]                        = "Channel",
  [CorTermGoal]                           = "Goal",
  [CorTermBridgeId]                       = "bridgeId",
  [CorTermBridgeOptions]                  = "bridgeOptions",
  [CorTermPlugin]                         = "plugin",
  [CorTermChannelTarget]                  = "channelTarget",
  [CorTermChannelKind]                    = "channelKind",
  [CorTermChannelDirection]               = "channelDirection",
  [CorTermRetention]                      = "retention",
  [CorTermCodec]                          = "codec",
  [CorTermEntityAttribute]                = "entityAttribute",
  [CorTermStatusReason]                   = "statusReason",
  [CorTermGoals]                          = "goals",
  [CorTermGoalId]                         = "goalId",
  [CorTermGoalRequest]                    = "goalRequest",
  [CorTermGoalFeedback]                   = "goalFeedback",
  [CorTermGoalResult]                     = "goalResult",
  [CorTermLangProperties]                 = "langProperties",
  [CorTermServiceDescription]             = "ServiceDescription",
  [CorTermServiceRegistration]            = "ServiceRegistration",
  [CorTermServiceExecution]               = "ServiceExecution",
  [CorTermGroupedServiceExecution]        = "GroupedServiceExecution",
  [CorTermCombinedServiceExecution]       = "CombinedServiceExecution",
  [CorTermCombinedServiceTemplate]        = "CombinedServiceTemplate",
  [CorTermAttributeSelectorType]          = "AttributeSelector",
  [CorTermAttributeSelector]              = "attributeSelector",
  [CorTermServiceName]                    = "serviceName",
  [CorTermServiceInformation]             = "serviceInformation",
  [CorTermServiceDescriptionInEntity]     = "serviceDescriptionInEntity",
  [CorTermExecutionStatus]                = "executionStatus",
  [CorTermCombinationMethod]              = "combinationMethod",
  [CorTermServiceExecutions]              = "serviceExecutions",
  [CorTermServices]                       = "services",
  [CorTermTemplateName]                   = "templateName",
  [CorTermEntityTypeMember]               = "entityType",
  [CorTermInputSchema]                    = "inputSchema",
  [CorTermOutputSchema]                   = "outputSchema",
  [CorTermExecutionInput]                 = "executionInput",
  [CorTermExecutionOutput]                = "executionOutput",
  [CorTermExecutionError]                 = "executionError",
  [CorTermExecutionProgress]              = "executionProgress",
  [CorTermExecutionStartedAt]             = "executionStartedAt",
  [CorTermExecutionEndedAt]               = "executionEndedAt",
  [CorTermExecutionTimeout]               = "executionTimeout",
  [CorTermServiceTemplateId]              = "serviceTemplateId",
};



// -----------------------------------------------------------------------------
//
// ldCoreTermIdsInit -
//
int ldCoreTermIdsInit(CorAlloc* kaP)
{
  for (int id = 1; id < CorTermLast; id++)
  {
    if (ldCoreTermNameV[id] == NULL)
    {
      COR_E("CorTerm %d has no name in ldCoreTermNameV", id);
      return -1;
    }
  }

  const char* missing = NULL;

  if (corLdCoreTermIdsSet(ldCoreTermNameV, CorTermLast, kaP, &missing) != 0)
  {
    COR_E("The core context term '%s' has no CorTerm - the enum does not match the core context", (missing != NULL) ? missing : "(unknown)");
    return -1;
  }

  return 0;
}
